name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4
        
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Construção da Imagen Docker
        run: echo "Executando o Comando docker build"
        
      - name: Envio da Imagen Docker
        run: echo "Executando o Comando docker push"
        
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar no AWS
        run: echo "Executando o comando AWS configure"
      - name: Construção o Kubectl
        run: echo "Executando o Comando AWS eks update-kubeconfig"
      - name: Deploy dos manifestos Kubernetes
        run: echo "Executando o Comando kubectl apply"

